### PR TITLE
feat(autocomplete): Be able to search on autocomplete without accents

### PR DESCRIPTION
**Pull request by JoydS**
Hello,

The idea of the PR is to be enable to search with and without accent on autocomplete.

If you have the option "États Unis" (in French for exemple), today you need to search "É" to find it, "E" doesn't work.

Im available if you need more informations or if you need me to add something to the pull request.

Have a nice day,

### CODE REVIEW

**Comment by dudyn5ky1** [comment]
Hello @JoydS , 

Thanks for the PR!

I'm finishing `2.0.0`, and SelectPure will have different interface and features (including autocomplete and ability to provide a custom filtering method).

I can merge your PR to develop and then release it as a `0.6.x` version, but it will not be included in the `2.0.0`. 

If you can solve conflicts, that would be great (I've just rebased `develop` to the latest `0.x` version).

Cheers!

**Comment by JoydS** [comment]
Hello @dudyn5ky1,

No problem, tagged as 0.6.x is good enough for now :)

The branch is rebase, you can merge it whenever you want to.

Thank you,

**Comment by JoydS** [comment]
Hello @dudyn5ky1, Im not sure that you pushed the tag 0.6.3 :)

**Comment by dudyn5ky1** [comment]
@JoydS it's published to [npm](https://www.npmjs.com/package/select-pure/v/0.6.3). 

Pushed the tag as well. Thanks for the PR!

**Pull request merged**
