### PR TITLE
Match in middle of strings

### PR DESCRIPTION
**Pull request by edgarcosta**
Just a replacement of `startsWith`  with `includes`.

Obviously, one could make this more advanced and make it an option.

### CODE REVIEW

**Comment by dudyn5ky1** [comment]
Hi @edgarcosta.

I'm ok with that, but it will probably become a Breaking change, since someone may rely on the `startsWith` implementation.

Also, are the tests passing after this change?

**Comment by edgarcosta** [comment]
@dudyn5ky1, if you are afraid of backward compatibility, then we should make it an option. Where the default is the `startsWith`. 
I think I can figure that out.
Nonetheless, I should point out that I'm a novice when it comes to javascript development. In particular, I don't know how one would run tests, but happy to learn.

**Comment by dudyn5ky1** [comment]
@edgarcosta yes, an option sound great.

You can run tests with the following command ‘yarn test’.

**Comment by dudyn5ky1** [comment]
Closing this, since version 2 is coming soon.

**Pull request closed without merging**
